package com.foxykeep.fbpuzzle.config;

@SuppressWarnings("unused")
public class LogConfig {

    private LogConfig() {
    }

    /**
     * Log Level variables
     */
    private static final int FBP_LOG_LEVEL_DEBUG = 3;
    private static final int FBP_LOG_LEVEL_WARNING = 2;
    private static final int FBP_LOG_LEVEL_ERROR = 1;
    private static final int FBP_LOG_LEVEL_NONE = 0;

    /**
     * Set this flag to {@link LogConfig#FBP_LOG_LEVEL_NONE} when releasing your application in order to remove all logs generated.
     */
    private static final int FBP_LOG_LEVEL = FBP_LOG_LEVEL_DEBUG;

    public static final boolean FBP_DEBUG_LOGS_ENABLED = (FBP_LOG_LEVEL_DEBUG == FBP_LOG_LEVEL);
    public static final boolean FBP_WARNING_LOGS_ENABLED = FBP_DEBUG_LOGS_ENABLED || (FBP_LOG_LEVEL == FBP_LOG_LEVEL_WARNING);
    public static final boolean FBP_ERROR_LOGS_ENABLED = FBP_WARNING_LOGS_ENABLED || (FBP_LOG_LEVEL == FBP_LOG_LEVEL_ERROR);

    /**
     * Set this flag to false to disabled all the logs generated by the Puzzle component.
     */
    private static final boolean FBP_PUZZLE_LOGS_STATE = true;

    public static final boolean FBP_PUZZLE_LOGS_ENABLED = FBP_PUZZLE_LOGS_STATE && FBP_DEBUG_LOGS_ENABLED;
}
